- name: netology-ml
  hosts: all
  become: yes

  vars:
    packages:
      - net-tools
      - git
      - tree
      - htop      	
      - mc
      - vim
      
  tasks:

  - name: Task ping
    ping:

  - name: Task yum update
    yum:
      update_cache: yes

  - name: Installing package
    yum:
      name: "{{ packages }}"
      state: latest

  - name: Copy File
    copy:
      src: test.txt
      dest: /home/ansible/files
      mode: 0777

  - name: Create Groups
    group:
      name: "{{item}}"
      state: present
    loop:
      - devops_1
      - test_1

  - name: Create User
    user:
      name: "{{item.client_name}}"
      shell: /bin/bash/
      groups: devops_1, test_1
      append: yes
      home: "/home/{{item.home_dir}}"
    with_items:
      - {client_name: client1, home_dir: devops_1}
      - {client_name: client2, home_dir: test_1}