## HomeWork - Functions

### Помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

#### Общие требования к программе:
•	код должен быть грамотно декомпозирован (каждая функция отвечает за свою конкретную задачу, дублирующийся функционал переиспользуется, а его код не повторяется);

•	в коде отсутствуют глобальные переменные (за исключением documents и directories);

•	пользовательский ввод обрабатывается в цикле while до тех пор, пока пользователь явно не завершит программу (вводом команды "q").

In [1]:
# Исходные данные имеют следующую структуру:
    
# перечень всех документов

documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]

# перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)

directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}


### Задание 1

### Пункт 1. Пользователь по команде "p" может узнать владельца документа по его номеру

Примеры работы:
1.
Введите команду:
p

Введите номер документа:
10006
Результат:
Владелец документа: Аристарх Павлов

2.
Введите команду:
p

Введите номер документа:
12345
Результат:
Документ не найден в базе

In [2]:
def document_owner(documents, number_doc = -1):
    """
    Функция для определения владельца документа по номеру документа
    
    На вход подается список из словарей со структурой: 
    {'type': 'xxx', 'number': 'yyyyyy', 'name': 'zzzzzzzzzzzz'}
    
    Возвращает:
                имя владельца: если номер найден 
            или
                None: если документ в базе не найден
    
    """
    if number_doc == -1:
        number_doc = input('Введите номер документа: ')
        
    for i in documents:
        if i['number'] == number_doc:
            return i['name']
    return
    
    
# document_owner(documents)
# print(document_owner(documents))
# ?document_owner

n_doc = document_owner(documents)
if n_doc is None:
    print(f"Документ не найден в базе")
else:
    print(f"Владелец документа: {n_doc}")

Введите номер документа: 0
Документ не найден в базе


### Задание 1

### Пункт 2. Пользователь по команде "s" может по номеру документа узнать на какой полке он хранится

Примеры работы:
1.
Введите команду:
s

Введите номер документа:
10006
Результат:
Документ хранится на полке: 2

2.
Введите команду:
p

Введите номер документа:
12345
Результат:
Документ не найден в базе

In [6]:
# считаю что если документ не найден на полке, то такого документа нет в базе (то есть нет в documents)
def document_directories(directories, number_doc = -1):
    """
    Функция для определения на какой полке хранится документ
    
    Возвращает:
                номер полки на которой находится документ
            или
                0 если документ не найден в базе

    """
    if number_doc == -1:
        number_doc = input('Введите номер документа: ')
    
    for i, shelf in enumerate(directories.values()):
        if number_doc in shelf:
            return i+1
    return 0
    
n_shelf = document_directories(directories)
if n_shelf > 0:
    print(f'Документ хранится на полке: {n_shelf}')
else:
    print(f'Документ не найден в базе')

Введите номер документа: 0
Документ не найден в базе


### Задание 1

### Пункт 3. Пользователь по команде "l" может увидеть полную информацию по всем документам

Пример работы:
Введите команду:
l
Результат:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

In [7]:
# В данном случае предусмотрел дополнительную проверку на точ то документ не найден на полке...

def list_document(documents, directories):
    """
    Функция для вывода полной информации по документам
    
    Выводит информацию о всех документах и полках, где документы хранятся...
    """
    for i in documents:
        num_shelf = document_directories(directories, number_doc = i['number'])
        if num_shelf > 0:
            print(f"№: {i['number']}, тип: {i['type']}, владелец: {i['name']}, полка хранения: {num_shelf}")
        else:
            print(f"№: {i['number']}, тип: {i['type']}, владелец: {i['name']}, полка хранения: не известно")

list_document(documents, directories)

№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2


### Задание 1

### Пункт 4. Пользователь по команде "ads" может добавить новую полку
Примеры работы:
1.
Введите команду:
ads

Введите номер полки:
10
Результат:
Полка добавлена. Текущий перечень полок: 1, 2, 3, 10.
2.
Введите команду:
ads

Введите номер полки:
1
Результат:
Такая полка уже существует. Текущий перечень полок: 1, 2, 3.

In [5]:
def dict_keys_to_list(dict_keyss):
    """
    Преобразование словаря ключей (списка) в строку
    
    """
    return ", ".join(dict_keyss)

dict_keys_to_list((['1', '2', '3', '10']))

'1, 2, 3, 10'

In [9]:
def add_shelf(directories):
    """
    Функция для добавления новой полки
    
    """
    number_shelf = input('Введите номер полки: ')
    ald_length_shelf = len(directories)
    directories.setdefault(number_shelf)
    if len(directories) > ald_length_shelf:
        print(f'Полка добавлена. Текущий перечень полок: {dict_keys_to_list(directories.keys())}.')
    else:
        print(f'Такая полка уже существует. Текущий перечень полок: {dict_keys_to_list(directories.keys())}.')
    
    
add_shelf(directories)

Введите номер полки: 0
Такая полка уже существует. Текущий перечень полок: 1, 2, 3, 0.


### Задание 1

### Пункт 5. Пользователь по команде "ds" может удалить существующую полку из данных (только если она пустая)
Примеры работы:
1.
Введите команду:
ds

Введите номер полки:
3
Результат:
Полка удалена. Текущий перечень полок: 1, 2.

2.
Введите команду:
ds

Введите номер полки:
1
Результат:
На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 3.

3.
Введите команду:
ds

Введите номер полки:
4
Результат:
Такой полки не существует. Текущий перечень полок: 1, 2, 3.

In [34]:
def del_shelf(directories):
    """
    Функция для удаления полки
    
    """
    number_shelf = input('Введите номер полки: ')
    # number_shelf = '1'
    if number_shelf in directories:
        if directories[number_shelf] != None and len(directories[number_shelf]) > 0:
            print(f'На полке есть документ(ы), удалите их перед удалением полки. Текущий перечень полок: {dict_keys_to_list(directories.keys())}.')
        else:
            del(directories[number_shelf])
            print(f' Полка удалена. Текущий перечень полок: {dict_keys_to_list(directories.keys())}.')
    else:
        print(f'Такой полки не существует. Текущий перечень полок: {dict_keys_to_list(directories.keys())}.')

    print
    
del_shelf(directories)

Введите номер полки: 1
1
На полке есть документ(ы), удалите их перед удалением полки. Текущий перечень полок: 1, 2.


### Задание 2

### Пункт 1. Пользователь по команде "ad" может добавить новый документ в данные

Примеры работы:
1.
Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
3

Результат:
Документ добавлен. Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№: 42, тип: multipassport, владелец: R2D2, полка хранения: 3




2.
Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
4

Результат:
Такой полки не существует. Добавьте полку командой as. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

In [27]:
# Перед добавлением документа дополнительно проверяю, что такого документа нет в базе.
# Если есть, то не добавляю, выдаю сообщение...

def add_document(documents, directories):
    """
    Функция для добавления нового документа
    
    
    """
    num_doc = input('Введите номер документа: ')
    type_doc = input('Введите тип документа: ')
    owner_doc = input('Введите владельца документа: ')
    shelf_doc = input('Введите полку для хранения: ')

#     num_doc = '42'
#     type_doc = 'multipassport'
#     owner_doc = 'R2D2'
#     shelf_doc = '3'
    
#     num_doc = '423'
#     type_doc = 'multipassport'
#     owner_doc = 'R2D2_'
#     shelf_doc = '7'

#     num_doc = '2207 876234'
#     type_doc = 'passport'
#     owner_doc = 'Василий Гупкин'
#     shelf_doc = '3'
        
    if shelf_doc in directories:
        current_owner_doc = document_owner(documents, num_doc)
        if current_owner_doc is not None:
            print(f'Такой документ уже существует в базе. Не добавляю документ повторно...')
        
        else:
            # добавление документа на полку
            directories[shelf_doc].append(num_doc)
            
            # добавление нового документа в базу
            documents.append({'type': type_doc, 'number': num_doc, 'name': owner_doc})
    
    else:
        print(f'Такой полки не существует. Добавьте полку командой as.')
    
    print('\nТекущий список документов:')
    list_document(directories)
    
    
add_document(documents, directories)

Введите номер документа: 10006
Введите тип документа: fg
Введите владельца документа: g
Введите полку для хранения: g
Такой полки не существует. Добавьте полку командой as.

Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2


### Задание 2

### Пункт 2. Пользователь по команде "d" может удалить документ из данных

Примеры работы:
1.
Введите команду:
d

Введите номер документа:
10006
Результат:
Документ удален. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1



2.
Введите команду:
d

Введите номер документа:
123456
Результат:
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

In [29]:
def del_document(documents, directories):
    """
    Функция для удаления документа из базы
    
    
    """
    num_doc = input('Введите номер документа: ')
    
#    num_doc = '42'
#    num_doc = '11-2'
#    num_doc = '10006'
#    num_doc = '423'
#    num_doc = '2207 876234'
    
    number_dir = document_directories(directories, num_doc)
    if number_dir > 0:
        # удаляем документ с полки:
        number_dir_str = str(number_dir)
        directories[number_dir_str].remove(num_doc)
      
        # удаляем сам документ:
        del(documents[number_dir])
        
        print('Документ удален.')
    
    else:
        print(f'Документ не найден в базе')

    print('\nТекущий список документов:')
    list_document(directories)

    
    
del_document(documents, directories)

Введите номер документа: 0
Документ не найден в базе

Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2


### Задание 2

### Пункт 3. Пользователь по команде "m" может переместить документ с полки на полку

Примеры работы:

1.
Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
3
Результат:
Документ перемещен. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 3
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2



2.
Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
10
Результат:
Такой полки не существует. Текущий перечень полок: 1, 2, 3.



3.
Введите команду:
m

Введите номер документа:
42
Введите номер полки:
2
Результат:
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

In [53]:
def move_document(directories):
    """
    Функция для переноса документа из базы
    
    
    """
        
    num_doc = input('Введите номер документа: ')

#    num_doc = '42'
#    num_doc = '11-2'
#    num_doc = '10006'
#    num_doc = '423'
#    num_doc = '2207 876234'


    number_dir = document_directories(directories, num_doc)
    if number_dir > 0:
        num_dir_new = input('Введите номер папки: ')
        # проверим есть ли такая папка:
        if num_dir_new in directories:
            # удаляем документ со старой полки:
            directories[str(number_dir)].remove(num_doc)
            
            # добавляем документ на новую полку:
            directories[num_dir_new].append(num_doc)
            print('Документ перемещен. ')
            
        else:
            print('Такой полки не существует.')
        
    else:
        print(f'Документ не найден в базе')
   
    print('\nТекущий список документов:')
    list_document(directories)
    
move_document(directories)

Введите номер документа: 10006
Введите номер папки: 1
Документ перемещен. 

Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 1


In [8]:
def main(documents):
    while True:
        command_user = input('Введите команду:\n   p - владелец по номеру документа;\n'
                             +'   s - полка на которой хранится документ;\n   l - полный список документов;\n'
                             +'   ads - добавить полку; \n   ds - удалить полку;\n   ----------------------\n'
                             +'   ad - добавить новый документ;\n   d - удалить документ;\n'
                             +'   m - переместить документ с полки на полку;\n'
                             +'   ----------------------\n   q-завершить программу\n\n => ')
        print()
        # Определение владельца документа по номеру документа
        if command_user == 'p':
            #document_owner(documents)
            doc_owner = document_owner(documents)
            if doc_owner is None:
                print(f"Документ не найден в базе")
            else:
                print(f"Владелец документа: {doc_owner}")
            
        # Определение на какой полке хранится документ
        elif command_user == 's':
            print(document_directories(directories))
            
        # Вывод полной информации по документам
        elif command_user == 'l':
            list_document(documents, directories)
            
        # добавление новой полки
        elif command_user == 'ads':
            add_shelf(directories)
            
        # удаление полки (если не пустая)
        elif command_user == 'ds':
            del_shelf(directories)
            
        # -------------------------------
        # добавление документа
        elif command_user == 'ad':
            add_document(documents, directories)
            
        # удаление документа из базы
        elif command_user == 'd':
            del_document(documents, directories)
            
        # Перемещение документа с полки на полку
        elif command_user == 'm':
            move_document(directories)
            
        # -------------------------------
        
        # Завершение программы
        elif command_user.lower() == 'q':
            print('До свидания!')
            break
            
        # Проверка на незнакомые команды
        else:
            print('Данная команда не предусмотренна ')
        
        print()

main(documents)

Введите команду:
   p - владелец по номеру документа;
   s - полка на которой хранится документ;
   l - полный список документов;
   ads - добавить полку; 
   ds - удалить полку;
   ----------------------
   ad - добавить новый документ;
   d - удалить документ;
   m - переместить документ с полки на полку;
   ----------------------
   q-завершить программу

 => l

№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

Введите команду:
   p - владелец по номеру документа;
   s - полка на которой хранится документ;
   l - полный список документов;
   ads - добавить полку; 
   ds - удалить полку;
   ----------------------
   ad - добавить новый документ;
   d - удалить документ;
   m - переместить документ с полки на полку;
   ----------------------
   q-завершить программу

 => q

До свидания!
